apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
  labels:
    app: k8s-demo
spec:
  storageClassName: slow
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data01"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mypvc
  labels:
    app: k8s-demo
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 2Gi
  storageClassName: slow
  
